language: node_js
node_js:
- '6'
install:
- travis_retry $TRAVIS_BUILD_DIR/go setup
script:
- "$TRAVIS_BUILD_DIR/go test && $TRAVIS_BUILD_DIR/go jar && cd $TRAVIS_BUILD_DIR/backend && ./lein deploy"

sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.lein"
env:
  global:
    secure: ZaaxMFbGeua0aihQ4HxDBxrF3mXEPhOypEl046lQ+lTjK0yodhpRUWqEPdiWgMA48oQ7HlorwCf+etm6/oU+BcZohxcG0BRBGLn43yhE3YSB7IhrMCly9bYUTDcCF9TRe0keyQIoZQsUwwbJRsbN/QWVvCNOkoe4jV8hA1KFUdLC9pdpQ4TN/2YDgSlRRBUt8iMi6okYwJcwtC1HGYXKKAhoXLOQCLYwQ2rmBNhhyTSE6l+kZ88a79RcN4Ab9L5f6NxOQrYp/n7XdPcxx2J+wRrWYdxQov8PD5wEDu7Miai22hsTO0lirOaoB/2fuJYV7BZz3O8qaFyvlUE88yEjgieqn2lPh6mhgOp7tOiRQuDaXnysX+pd631eSvPmhWWRU4uNAixkTVD04fEpG7+bvKkwrDhqPXSFmcYpz+QkTYCu0JwYEFHqPTc4a3vRfGu/6Q7p4pWvY0eJxFl+znnNw1pVn3JkkoDe8stP7Z92ferg9m5zkkThqtaaKZ/PvHhlAYE7vNayKnKFWZljZM8PGoLJV5Sv25E52t99YlwU1VPlc+0Es1vvCcSJmdOF9ujLIJa52L9OLuWjfaQPAjewPLjgR4IcFMKtoW0VneICc2pwXFfVJ+DmpvAPfPpcTodQez3gPGuowbckeDNkA/FsdYFRmoB9yBwqfEFKqwxDzRM=

before_deploy:
- cd $TRAVIS_BUILD_DIR/example-pipeline
deploy:
  api_key:
    secure: pboS2xCL7MbGjzRDCmLwTsl8CXAjPhLmVLTKca/ulja+XYIMBead4oESLhsrpWU8M3a83JfoQ4/KsgdbGvgRnEvGtR9S/E01UtxriMcGEBehRa+QY4drjn3McuqHMd01zNQNVm7ivMGLQdpkrDISiLj44f5ozapyFf5bP2Coj0ypR4M9xbtn2RRMLHBEPCESDr5NR7RchFTCvwva1u93YPWycx6TbNejKIpunD/58O6gWu671wLUtUbTADdJw7JWj9+YFsdwZfZEivQ7Fzj7rRUZY8XnLuZghLEJmpExjMLgba5X2wSZbdfZOZxFGMJfa/NtJcS0d2fGzGxY7WP6taW7m/S3TuhS55Y8cI3bXierP97dl8ce0+zymcZu/dn8wUKP+7MLuPGvP80GHql11OVYCb5zCqTCHKw+epnYNJNStx+zURNe7cVJj6zbCubGyVOuyScg3gskbdRus2tHYVg8kFAr17asTRKog58ET6TVqfDVhPmTX/DHTeQguACAF4gvnAkTO6WfAdOkY9efxeRzlPSMQVd8+4oeLCor3QRtRIPAQ6s3kEv9XroOgClMMBeBKwwi5h5Ay4uGIRDHRApN3XSQRcpTVu6EdZI3AdK3FPfjGqRXk6SVIpvsrUY8KcOx8UjKDkMmNa7Nv+I5JO5YL+CYyWYuH7EkLVgl0Ok=
  buildpack: clojure
  provider: heroku
  app: lambdaui-snapshot
